// Vercel serverless function — "Edit with Claude" AI page editor.
//   POST /api/ai-edit  { page, instruction, history? }
//
// Flow: verify the caller's Supabase session -> read the target page from the
// STAGING branch on GitHub -> ask Claude for the minimal body edit as a
// forced tool call -> apply the find/replace edits -> commit to STAGING only
// -> best-effort activity_log entry. NEVER writes to main.
//
// Server-only env (never exposed to the browser):
//   ANTHROPIC_API_KEY, ANTHROPIC_MODEL (default "claude-sonnet-5"),
//   GITHUB_TOKEN, GITHUB_REPO, GITHUB_STAGING_BRANCH (default "staging"),
//   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY.
// Reuses the browser anon key (SUPABASE_ANON_KEY | VITE_SUPABASE_ANON_KEY)
// purely to verify the caller's access token.
import { createClient } from '@supabase/supabase-js';
import { getAuthedUser } from '../server/auth.js';

const GH_API = 'https://api.github.com';

// Roles allowed to make edits (edits land on staging only).
const EDIT_ROLES = new Set(['owner', 'editor', 'author']);
const ANTHROPIC_API = 'https://api.anthropic.com/v1/messages';

function ghHeaders() {
  return {
    Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'ph-website-admin',
  };
}

function cfg() {
  return {
    repo: process.env.GITHUB_REPO,
    staging: process.env.GITHUB_STAGING_BRANCH || 'staging',
    model: process.env.ANTHROPIC_MODEL || 'claude-sonnet-5',
    supabaseUrl: process.env.SUPABASE_URL,
    anonKey: process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY,
    serviceKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
  };
}

async function readBody(req) {
  if (req.body && typeof req.body === 'object') return req.body;
  if (typeof req.body === 'string' && req.body) {
    try { return JSON.parse(req.body); } catch { return {}; }
  }
  return await new Promise((resolve) => {
    let raw = '';
    req.on('data', (c) => { raw += c; });
    req.on('end', () => {
      try { resolve(raw ? JSON.parse(raw) : {}); } catch { resolve({}); }
    });
    req.on('error', () => resolve({}));
  });
}

// Guardrails embedded from the site's CLAUDE.md operating rules.
const SYSTEM_PROMPT = `You are the "Edit with Claude" assistant for the Project H.O.O.D. website admin.
Non-technical staff describe changes in plain English; you edit the website's source.

CRITICAL — HOW THIS SITE IS BUILT:
The projecthood.org pages are GENERATED by a Python script, _build.py, which contains each page's
full HTML body inside template strings. The .html files are build OUTPUTS and are overwritten on every
build. Therefore you must make edits inside _build.py (the source), NOT in any .html file — otherwise
the change is wiped on the next rebuild. You will be given the full _build.py and told which page to edit.

HARD RULES (never break these):
- Edit ONLY the requested page's BODY content (its headlines, paragraphs, sections, images, links) inside
  its template string in _build.py. Find that page's section first.
- Make the MINIMAL change. Do not rewrite or reformat unrelated markup or other pages.
- NEVER change Python code, function definitions, the render()/HEAD/nav/footer template strings, f-string
  placeholders (e.g. {a_programs}, {active}), imports, or logic. Only change human-visible HTML text/markup
  within the target page's body.
- Use existing brand CSS classes and variables (var(--green), var(--red), var(--yellow), .bg-green,
  .bg-red, .bg-offwhite, .video-frame). NEVER introduce raw hex color values.
- Keep section backgrounds alternating; keep valid, balanced HTML; keep the file valid Python (don't break
  quotes/escaping inside the strings).
- All work lands on "staging" and stays there until a human publishes — nothing you do goes live.
- Do NOT swap external destinations (Donate->NetworkForGood, Walk With Us->Tiltify, Volunteer/Contact->Google Forms).

You MUST respond by calling the "stage_edits" tool. Every edit's "find" must be an EXACT, UNIQUE substring
copied verbatim from _build.py (include enough surrounding context to be unique). If you cannot safely make
the change, return an empty edits array and explain why in "reply".`;

const STAGE_EDITS_TOOL = {
  name: 'stage_edits',
  description: 'Stage minimal find/replace edits to the current page and return a friendly chat reply.',
  input_schema: {
    type: 'object',
    properties: {
      reply: {
        type: 'string',
        description: 'A short, friendly chat reply to the user describing what you did (or why you could not).',
      },
      summary: {
        type: 'string',
        description: 'One-line plain-English summary of the change (used as the commit message and activity log entry).',
      },
      edits: {
        type: 'array',
        description: 'The minimal set of find/replace edits. May be empty if no change should be made.',
        items: {
          type: 'object',
          properties: {
            find: {
              type: 'string',
              description: 'An exact substring currently in the file. Must be unique in the file.',
            },
            replace: {
              type: 'string',
              description: 'The replacement text.',
            },
          },
          required: ['find', 'replace'],
        },
      },
    },
    required: ['reply', 'summary', 'edits'],
  },
};

function countOccurrences(haystack, needle) {
  if (!needle) return 0;
  let count = 0;
  let idx = haystack.indexOf(needle);
  while (idx !== -1) {
    count += 1;
    idx = haystack.indexOf(needle, idx + needle.length);
  }
  return count;
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { repo, staging, model, supabaseUrl, anonKey, serviceKey } = cfg();

  if (!process.env.ANTHROPIC_API_KEY) {
    return res.status(500).json({ error: 'AI editor is not configured (missing ANTHROPIC_API_KEY).' });
  }
  if (!process.env.GITHUB_TOKEN || !repo) {
    return res.status(500).json({ error: 'AI editor is not configured (missing GITHUB_TOKEN / GITHUB_REPO).' });
  }
  if (!supabaseUrl || !anonKey) {
    return res.status(500).json({ error: 'AI editor is not configured (missing Supabase URL / anon key).' });
  }

  try {
    // 1) AUTH GATE — require a valid Supabase session, then require an
    //    edit-capable role. Viewers (and anything else) are read-only.
    const authed = await getAuthedUser(req);
    if (authed.error) {
      if (authed.error === 'unauthenticated') {
        return res.status(401).json({ error: 'Not signed in. Please sign in and try again.' });
      }
      if (authed.error === 'invalid') {
        return res.status(401).json({ error: 'Your session is invalid or expired. Please sign in again.' });
      }
      return res.status(500).json({ error: 'AI editor is not configured (auth).' });
    }
    if (!EDIT_ROLES.has(authed.role)) {
      return res.status(403).json({ error: 'Your account is read-only. Ask an owner for editor access.' });
    }
    const actor = authed.userId;

    // Validate body.
    const body = await readBody(req);
    const page = (body.page || '').toString().trim();
    const instruction = (body.instruction || '').toString().trim();
    const history = Array.isArray(body.history) ? body.history : [];

    if (!page) return res.status(400).json({ error: 'A page is required.' });
    if (!instruction) return res.status(400).json({ error: 'Please describe the change you want.' });
    // Only allow relative repo paths (no traversal, no leading slash).
    if (page.includes('..') || page.startsWith('/')) {
      return res.status(400).json({ error: 'Invalid page path.' });
    }

    // 2) Read the SITE BUILD SCRIPT from the STAGING branch.
    //    IMPORTANT: the .html files are generated from _build.py on every build,
    //    so edits must be made in _build.py to persist through the rebuild.
    const BUILD_FILE = '_build.py';
    const getUrl = `${GH_API}/repos/${repo}/contents/${encodeURIComponent(BUILD_FILE)}?ref=${encodeURIComponent(staging)}`;
    const getRes = await fetch(getUrl, { headers: ghHeaders() });
    if (!getRes.ok) {
      const text = await getRes.text();
      return res.status(getRes.status).json({ error: `Couldn't read the site source from GitHub: ${text}` });
    }
    const fileData = await getRes.json();
    const sha = fileData.sha;
    const originalHtml = Buffer.from(fileData.content || '', 'base64').toString('utf8');

    // 3) Ask Claude for the edits (forced tool call).
    const historyText = history.length
      ? '\n\nEarlier in this conversation:\n' +
        history
          .slice(-8)
          .map((m) => `${m.role === 'assistant' ? 'Claude' : 'User'}: ${(m.text || '').toString()}`)
          .join('\n')
      : '';

    const userMessage =
      `The user is editing the "${page}" page of projecthood.org.\n\n` +
      `The user's request: ${instruction}${historyText}\n\n` +
      `Below is the FULL SOURCE of _build.py — the Python script that generates every page's HTML. ` +
      `Locate the section that builds the "${page}" page and make the MINIMAL change to the HTML text ` +
      `inside its template string to satisfy the request. Each "find" must be an exact, UNIQUE substring ` +
      `of this file (include enough surrounding context to guarantee uniqueness). Do NOT change Python ` +
      `code, f-string placeholders like {a_programs}, the render()/nav/footer/head templates, or anything ` +
      `outside the requested page's body content.\n\n` +
      `----- BEGIN _build.py -----\n${originalHtml}\n----- END _build.py -----`;

    const aiRes = await fetch(ANTHROPIC_API, {
      method: 'POST',
      headers: {
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model,
        max_tokens: 4000,
        system: SYSTEM_PROMPT,
        tools: [STAGE_EDITS_TOOL],
        tool_choice: { type: 'tool', name: 'stage_edits' },
        messages: [{ role: 'user', content: userMessage }],
      }),
    });

    if (!aiRes.ok) {
      const text = await aiRes.text();
      console.error('[ai-edit] Anthropic error:', aiRes.status, text);
      return res.status(502).json({ error: `The AI service returned an error (${aiRes.status}). Please try again.` });
    }

    const aiData = await aiRes.json();
    const toolUse = (aiData.content || []).find((c) => c.type === 'tool_use' && c.name === 'stage_edits');
    if (!toolUse || !toolUse.input) {
      return res.status(502).json({ error: "The AI didn't return a usable edit. Please rephrase and try again." });
    }

    const { reply = '', summary = 'AI edit', edits = [] } = toolUse.input;

    // 4+5) Apply edits and commit to STAGING (never main), with retry on
    //      concurrent-edit conflicts. Because all pages live in _build.py, two
    //      people editing at once contend on the same file. If GitHub rejects our
    //      commit because the file changed underneath us (409/422), we re-read the
    //      latest _build.py, re-apply the SAME edits, and try again.
    const applyEdits = (source) => {
      let out = source;
      const applied = [];
      const skipped = [];
      for (const edit of Array.isArray(edits) ? edits : []) {
        const find = (edit?.find ?? '').toString();
        const replace = (edit?.replace ?? '').toString();
        if (!find) { skipped.push({ reason: 'empty-find', find }); continue; }
        const occ = countOccurrences(out, find);
        if (occ === 0) { skipped.push({ reason: 'not-found', find }); continue; }
        if (occ > 1) { skipped.push({ reason: 'not-unique', find }); continue; }
        out = out.replace(find, replace);
        applied.push({ find, replace });
      }
      return { out, applied, skipped };
    };

    let currentSha = sha;
    let currentSource = originalHtml;
    let commitSha = null;
    let applied = [];
    let skipped = [];

    for (let attempt = 0; attempt < 3; attempt++) {
      const r = applyEdits(currentSource);
      applied = r.applied;
      skipped = r.skipped;

      // Nothing safely applied — either the request wasn't actionable, or another
      // edit just changed the same text. Commit nothing.
      if (applied.length === 0) {
        return res.status(200).json({
          reply: reply || "I couldn't apply that safely — the page may have just been edited by someone else. Please try again.",
          summary,
          editsApplied: 0,
          skipped,
          commitSha: null,
        });
      }

      const putRes = await fetch(`${GH_API}/repos/${repo}/contents/${encodeURIComponent(BUILD_FILE)}`, {
        method: 'PUT',
        headers: { ...ghHeaders(), 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: `AI edit (${page}): ${summary}`,
          content: Buffer.from(r.out, 'utf8').toString('base64'),
          sha: currentSha,
          branch: staging,
        }),
      });

      if (putRes.ok) {
        const putData = await putRes.json();
        commitSha = putData.commit?.sha || null;
        break;
      }

      // Conflict — someone else committed between our read and write. Re-read + retry.
      if (putRes.status === 409 || putRes.status === 422) {
        const reRead = await fetch(getUrl, { headers: ghHeaders() });
        if (reRead.ok) {
          const fd = await reRead.json();
          currentSha = fd.sha;
          currentSource = Buffer.from(fd.content || '', 'base64').toString('utf8');
          continue;
        }
      }

      // Any other error — fail out.
      const text = await putRes.text();
      console.error('[ai-edit] GitHub commit failed:', putRes.status, text);
      return res.status(putRes.status).json({ error: `Couldn't save the change to GitHub: ${text}` });
    }

    // Still not committed after retries — a persistent conflict.
    if (!commitSha) {
      return res.status(409).json({
        error: "Someone else is editing right now and your change couldn't be saved. Please send it again.",
        editsApplied: 0,
        skipped,
        commitSha: null,
      });
    }

    const editsApplied = applied.length;

    // 6) Best-effort activity_log entry (service role bypasses RLS).
    if (supabaseUrl && serviceKey) {
      try {
        const admin = createClient(supabaseUrl, serviceKey);
        await admin.from('activity_log').insert({
          kind: 'edit',
          summary: `${page}: ${summary}`,
          actor,
        });
      } catch (logErr) {
        console.error('[ai-edit] activity_log insert failed:', logErr);
      }
    }

    // 7) Respond. Include the applied edits (trimmed) so the UI can show a
    // human-readable before/after for review.
    const TRIM = 400;
    const appliedForClient = applied.map((e) => ({
      find: e.find.length > TRIM ? e.find.slice(0, TRIM) + '…' : e.find,
      replace: e.replace.length > TRIM ? e.replace.slice(0, TRIM) + '…' : e.replace,
    }));
    return res.status(200).json({
      reply: reply || 'Done — I staged that change for your review.',
      summary,
      editsApplied,
      applied: appliedForClient,
      skipped,
      commitSha,
    });
  } catch (err) {
    console.error('[ai-edit] error:', err);
    return res.status(500).json({ error: err.message || 'Unexpected error' });
  }
}
